services:
  - type: web
    name: Nature-s-Odyssey
    runtime: docker
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGO_URI
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true